cloud:
  aws:
    region:
      # AWS region
      static: <region>
      auto: false
    credentials:
      # I am role creds
      access-key: <key_id>
      secret-key: <key_value>
    end-point:
      # Queue url from AWS
      uri: <url>

razor:
  # https://razorpay.com/docs/payments/dashboard/account-settings/api-keys/
  key: <key_id>
  secret: <key_value>

email:
  user_name: <email_id>
  # https://support.google.com/mail/answer/185833?hl=en
  password: <app_password>
